create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  first_name text,
  last_name text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, first_name, last_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'last_name'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and is_admin = true
  );
$$;

create table if not exists public.membership_applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'draft'
    check (status in ('draft', 'pending', 'approved', 'rejected', 'action_required')),

  full_name text not null,
  gender text not null,
  date_of_birth date,
  age integer,
  phone_number text not null,
  email text not null,
  nida_number text not null,
  residential_address text not null,
  region text not null,
  district text not null,
  profession text not null,
  institution text default '',
  education_level text not null,
  work_experience_years integer,

  marital_status text not null default 'single'
    check (marital_status in ('single', 'married', 'widowed', 'divorced')),
  spouse_name text default '',
  spouse_phone text default '',
  member_group text not null default 'youth'
    check (member_group in ('youth', 'middle', 'elder')),

  parents jsonb not null default '[]'::jsonb,
  children jsonb not null default '[]'::jsonb,

  emergency_name text not null,
  emergency_relationship text not null,
  emergency_phone text not null,
  emergency_address text not null,
  wedding_sendoff_beneficiary text default '',
  declaration_accepted boolean not null default false,

  office_registration_number text default '',
  office_received_at date,
  office_received_by text default '',
  reviewed_at timestamptz,
  office_comments text default '',
  action_required_note text default '',

  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists membership_applications_set_updated_at on public.membership_applications;
create trigger membership_applications_set_updated_at
before update on public.membership_applications
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.membership_applications enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid() and is_admin = false);

drop policy if exists "Admins can manage profiles" on public.profiles;
create policy "Admins can manage profiles"
on public.profiles for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Members can read own applications" on public.membership_applications;
create policy "Members can read own applications"
on public.membership_applications for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Members can create own applications" on public.membership_applications;
create policy "Members can create own applications"
on public.membership_applications for insert
to authenticated
with check (user_id = auth.uid() and status in ('draft', 'pending'));

drop policy if exists "Members can update editable own applications" on public.membership_applications;
create policy "Members can update editable own applications"
on public.membership_applications for update
to authenticated
using (user_id = auth.uid() and status in ('draft', 'pending', 'action_required', 'rejected'))
with check (user_id = auth.uid() and status in ('draft', 'pending'));

drop policy if exists "Admins can update all applications" on public.membership_applications;
create policy "Admins can update all applications"
on public.membership_applications for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete applications" on public.membership_applications;
create policy "Admins can delete applications"
on public.membership_applications for delete
to authenticated
using (public.is_admin());

create index if not exists membership_applications_user_id_idx
on public.membership_applications(user_id);

create index if not exists membership_applications_status_idx
on public.membership_applications(status);
